server.port=8084
spring.application.name=ms-fulfillment

# Fila de origem, parametrizada via env
app.queue.fulfillment=${FULFILLMENT_QUEUE_NAME:sqs-poc-fulfillment-queue.fifo}

# Regiao AWS
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}

# SQS Listener tuning
spring.cloud.aws.sqs.listener.max-messages-per-poll=${SQS_MAX_MESSAGES_PER_POLL:10}
spring.cloud.aws.sqs.listener.poll-timeout=${SQS_WAIT_TIME_SECONDS:20}s
spring.cloud.aws.sqs.listener.max-concurrent-messages=10

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# MDC do correlation-id no log
logging.pattern.level=%5p [%X{correlationId:-}]
